# base_config.yaml
# =================
#
# Fichier unique de config pour tout le pipeline d'entraînement.
# Modifie ces valeurs pour tes expériences, puis relance simplement train.py.


# --------------------------------------------------------------------------
# Données
# --------------------------------------------------------------------------
data_dtype: float32       # Type numpy/torch du tableau des spectres (float16/float32/float64)

checkpoint_every: 100       # Fréquence de sauvegarde des checkpoints (en epochs)


# --------------------------------------------------------------------------
# DataLoader avancé (contrôle CPU/GPU, workers, transferts)
# --------------------------------------------------------------------------
batch_size: 32            # Nombre d'échantillons par batch
shuffle: false           # True pour mélanger à chaque epoch
num_workers: 4           # Nombre de workers pour le DataLoader (0 = main process)
pin_memory: true         # Active le pinning mémoire (recommandé si GPU)
prefetch_factor: 2       # Nombre de batches préchargés par worker (si num_workers>0)
persistent_workers: true # Garde les workers vivants entre les epochs (si num_workers>0)
dataset_cuda: false      # Si true, charge tout le dataset sur le GPU (déconseillé pour gros jeux de données)
move_batches_to_device: true  # Transfert chaque batch sur le device du modèle (recommandé)
non_blocking_transfer: true   # Utilise le transfert non bloquant CPU→GPU

# --------------------------------------------------------------------------
# Augmentation
# --------------------------------------------------------------------------
M_aug: 1                  # Combien de versions augmentées par spectre
vmin: -3                  # Vitesse min (m/s) pour décalage Doppler
vmax: +3                  # Vitesse max (m/s)
interpolate: "linear"     # Méthode d'interpolation
extrapolate: "linear"     # Méthode d'extrapolation hors bornes
out_dtype: float32        # Type de sortie des spectres augmentés (float16 économise ~50% mémoire GPU)

# --------------------------------------------------------------------------
# Modèle
# --------------------------------------------------------------------------
latent_dim: 3             # Dimension de l'espace latent (anciennement "S")

# Loss RV
sigma_v: 0.3              # Écart-type pour le bruit Doppler

# Loss reg
sigma_y: 1             # Écart-type pour le bruit de flux
k_reg_init: 0.              # Coefficient de régularisation pour la perte
cycle_length: 1000        # Nombre d'itérations pour le cycle de régularisation

# Loss consistency
get_aug_data: True         # Si True, calcule les données augmentées dans le forward pass et permet de calculer la loss de consistency
sigma_s: 0.0001              # Poids dans la loss de consistency

# Loss de smooth de l'activité
smooth_alpha: 1
smooth_order: 2

model_dtype: float32      # Type de données pour les poids du modèle (float16/float32/float64)

# --------------------------------------------------------------------------
# Mixed Precision Settings
# --------------------------------------------------------------------------
use_mixed_precision: true        # Activer la mixed precision
mixed_precision_dtype: float16   # Type de données pour les forward passes (float16)
autocast_enabled: true          # Utiliser autocast pour le forward pass
grad_scaler_enabled: true       # Utiliser GradScaler pour éviter les underflows
grad_scaler_init_scale: 65536.0 # Échelle initiale pour le gradient scaler
grad_scaler_growth_factor: 2.0  # Facteur de croissance du scaler
grad_scaler_backoff_factor: 0.5 # Facteur de réduction du scaler
grad_scaler_growth_interval: 2000 # Intervalle de croissance du scaler


# --------------------------------------------------------------------------
# Logging et plots
# --------------------------------------------------------------------------
save_losses_csv: true     # Sauver les losses dans un fichier CSV
csv_save_every: 100       # Fréquence de sauvegarde CSV (en epochs)
plot_every: 50             # Plot des losses tous les X epochs (0 = désactivé)
plot_rv_every: 50         # Plot des prédictions RV tous les X epochs (0 = désactivé)


b_obs_init : true_template
b_rest_init : true_template
# --------------------------------------------------------------------------
# Phases d'entraînement
# --------------------------------------------------------------------------
phases:
  - name: rvonly
    n_epochs: 200

    trainable_params:
      b_obs: false
      b_rest: false
      rvestimator: true
      spender: false

    optimizer: "torch.optim.Adam"
    optimizer_kwargs:
      lr: 0.001
      weight_decay: 0.0

    # early_stopping:
    #   patience: 20
    #   min_delta: 1e-6
    #   metric: "total" 
    #   mode: "min"
    #   restore_best_weights: true

  - name: joint
    n_epochs: 200
    
    trainable_params:
      b_obs: false
      b_rest: false
      rvestimator: true
      spender: true

    optimizer: "torch.optim.Adam"
    optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.0
    
    plot_activity_every: 20

    # scheduler: torch.optim.lr_scheduler.StepLR
    # scheduler_kwargs:
    #   gamma: 0.7
    #   step_size: 50