# colab_config.yaml
# =================
#
# Configuration spéciale pour Google Colab
# Utilise /content/exoplanets_llopis_mary_2025 comme répertoire racine des données


# --------------------------------------------------------------------------
# Données
# --------------------------------------------------------------------------
data_root_dir: "/content/exoplanets_llopis_mary_2025/data"  # Répertoire racine pour Colab
wavemin: 5000.0           # Longueur d'onde minimale (nm)
wavemax: 5050.0           # Longueur d'onde maximale (nm)
data_dtype: float32       # Type numpy/torch du tableau des spectres

checkpoint_every: 100       # Fréquence de sauvegarde des checkpoints (en epochs)

# --------------------------------------------------------------------------
# DataLoader
# --------------------------------------------------------------------------
batch_size: 16            # Nombre d'échantillons par batch
shuffle: false            # True pour mélanger à chaque epoch

# --------------------------------------------------------------------------
# Augmentation
# --------------------------------------------------------------------------
M_aug: 1                  # Combien de versions augmentées par spectre
vmin: -3                  # Vitesse min (m/s) pour décalage Doppler
vmax: +3                  # Vitesse max (m/s)
interpolate: "linear"     # Méthode d'interpolation
extrapolate: "linear"     # Méthode d'extrapolation hors bornes
out_dtype: float32        # Type de sortie des spectres augmentés

# --------------------------------------------------------------------------
# Modèle
# --------------------------------------------------------------------------
latent_dim: 3             # Dimension de l'espace latent (anciennement "S")
sigma_v: 0.3              # Écart-type pour le bruit Doppler
sigma_c: 0.0001              # Écart-type pour le bruit spectral
sigma_y: 1              # Écart-type pour le bruit de flux
k_reg_init: 0.               # Coefficient de régularisation pour la perte
cycle_length: 1000        # Nombre d'itérations pour le cycle de régularisation
b_obs_trainable: false    # Spectre observé fixe ou ajustable ?
b_rest_trainable: true    # Spectre template (repos) entraînable ?

# --------------------------------------------------------------------------
# Plotting
# --------------------------------------------------------------------------
plot_every: 10            # Fréquence des plots de losses (en epochs)
plot_dir: "/content/drive/MyDrive/aestra_results/figures"  # Sauvegarde sur Google Drive

# --------------------------------------------------------------------------
# Phases d'entraînement
# --------------------------------------------------------------------------
training_phases:
  rvonly:
    epochs: 100
    losses: ["rv"]
    lr: 0.001
    plot_spectra_every: 50
    spectra_plot_dir: "/content/drive/MyDrive/aestra_results/spectra"

  joint:
    epochs: 100  
    losses: ["rv", "fid", "c"]
    lr: 0.0005
    plot_spectra_every: 25
    spectra_plot_dir: "/content/drive/MyDrive/aestra_results/spectra"

# --------------------------------------------------------------------------
# CSV Logging
# --------------------------------------------------------------------------
csv_save_every: 25        # Sauvegarder CSV tous les 25 epochs
csv_dir: "/content/drive/MyDrive/aestra_results/logs"  # Répertoire pour les logs CSV

# --------------------------------------------------------------------------
# Checkpoints et modèles sauvegardés  
# --------------------------------------------------------------------------
model_save_dir: "/content/drive/MyDrive/aestra_results/models"  # Sauvegarder sur Google Drive
