# colab_test_config.yaml
# ======================
#
# Configuration de test pour diagnostiquer les problèmes sur Colab
# Utilise les chemins du repository cloné pour les tests initiaux


# --------------------------------------------------------------------------
# Données
# --------------------------------------------------------------------------
data_root_dir: "/content/exoplanets_llopis_mary_2025/data"  # Répertoire dans le repository cloné
wavemin: 5000.0           # Longueur d'onde minimale (nm)
wavemax: 5050.0           # Longueur d'onde maximale (nm)
data_dtype: float32       # Type numpy/torch du tableau des spectres
n_specs: 100              # Limiter le nombre de spectres pour test rapide

checkpoint_every: 10      # Fréquence de sauvegarde des checkpoints (en epochs) - réduite pour test

# --------------------------------------------------------------------------
# DataLoader
# --------------------------------------------------------------------------
batch_size: 8             # Taille de batch réduite pour test
shuffle: false            # True pour mélanger à chaque epoch

# --------------------------------------------------------------------------
# Augmentation
# --------------------------------------------------------------------------
M_aug: 1                  # Combien de versions augmentées par spectre
vmin: -3                  # Vitesse min (m/s) pour décalage Doppler
vmax: +3                  # Vitesse max (m/s)
interpolate: "linear"     # Méthode d'interpolation
extrapolate: "linear"     # Méthode d'extrapolation hors bornes
out_dtype: float32        # Type de sortie des spectres augmentés

# --------------------------------------------------------------------------
# Modèle
# --------------------------------------------------------------------------
latent_dim: 3             # Dimension de l'espace latent (anciennement "S")
sigma_v: 0.3              # Écart-type pour le bruit Doppler
sigma_c: 0.0001           # Écart-type pour le bruit spectral
sigma_y: 1                # Écart-type pour le bruit de flux
k_reg_init: 0.            # Coefficient de régularisation pour la perte
cycle_length: 1000        # Nombre d'itérations pour le cycle de régularisation
b_obs_trainable: false    # Spectre observé fixe ou ajustable ?
b_rest_trainable: true    # Spectre template (repos) entraînable ?

# --------------------------------------------------------------------------
# Plotting
# --------------------------------------------------------------------------
plot_every: 5             # Fréquence de plotting (en epochs) - réduite pour test
plot_dir: "/content/results/figures"  # Dossier accessible sur Colab

# --------------------------------------------------------------------------
# Phases d'entraînement (réduites pour test)
# --------------------------------------------------------------------------
phases:
  - name: rvonly
    n_epochs: 5           # Seulement 5 epochs pour test rapide
    optimizer: "torch.optim.Adam"
    optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.0
    b_obs_trainable: false
    b_rest_trainable: false

  - name: joint
    n_epochs: 5           # Seulement 5 epochs pour test rapide
    optimizer: "torch.optim.Adam"
    optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.0
    b_obs_trainable: false
    b_rest_trainable: true
    scheduler: "torch.optim.lr_scheduler.StepLR"
    scheduler_kwargs:
      step_size: 3
      gamma: 0.7
    plot_spectra_every: 5     # Plot des spectres à la fin
    spectra_plot_dir: "/content/results/spectra"

# --------------------------------------------------------------------------
# CSV Logging
# --------------------------------------------------------------------------
save_losses_csv: true
csv_save_every: 5         # Sauvegarder CSV toutes les 5 epochs
csv_dir: "/content/results/logs"
