# base_config.yaml
# =================
#
# Fichier unique de config pour tout le pipeline d'entraînement.
# Modifie ces valeurs pour tes expériences, puis relance simplement train.py.


# --------------------------------------------------------------------------
# Données
# --------------------------------------------------------------------------
data_root_dir: "/content/drive/MyDrive/PFE/data"     # Répertoire racine des données (peut être modifié pour Colab)
wavemin: 5000.0           # Longueur d'onde minimale (nm)
wavemax: 5050.0           # Longueur d'onde maximale (nm)
data_dtype: float32       # Type numpy/torch du tableau des spectres (float16/float32/float64)

checkpoint_every: 100       # Fréquence de sauvegarde des checkpoints (en epochs)

# --------------------------------------------------------------------------
# DataLoader
# --------------------------------------------------------------------------
batch_size: 16            # Nombre d'échantillons par batch
shuffle: false            # True pour mélanger à chaque epoch

# --------------------------------------------------------------------------
# Augmentation
# --------------------------------------------------------------------------
M_aug: 1                  # Combien de versions augmentées par spectre
vmin: -3                  # Vitesse min (m/s) pour décalage Doppler
vmax: +3                  # Vitesse max (m/s)
interpolate: "linear"     # Méthode d'interpolation
extrapolate: "linear"     # Méthode d'extrapolation hors bornes
out_dtype: float32        # Type de sortie des spectres augmentés (float16 économise ~50% mémoire GPU)

# --------------------------------------------------------------------------
# Modèle
# --------------------------------------------------------------------------
latent_dim: 3             # Dimension de l'espace latent (anciennement "S")
sigma_v: 0.3              # Écart-type pour le bruit Doppler
sigma_c: 0.0001              # Écart-type pour le bruit spectral
sigma_y: 1              # Écart-type pour le bruit de flux
k_reg_init: 0.               # Coefficient de régularisation pour la perte
cycle_length: 1000        # Nombre d'itérations pour le cycle de régularisation
b_obs_trainable: false    # Spectre observé fixe ou ajustable ?
b_rest_trainable: true    # Spectre template (repos) entraînable ?
model_dtype: float32      # Type de données pour les poids du modèle (float16/float32/float64)

# --------------------------------------------------------------------------
# Plotting
# --------------------------------------------------------------------------
plot_every: 100            # Fréquence de plotting (en epochs)
plot_dir: "/content/drive/MyDrive/PFE/reports/figures"  # Répertoire pour sauver les plots

# --------------------------------------------------------------------------
# Plotting des spectres avec raies G2
# --------------------------------------------------------------------------
zoom_window_angstrom: 10  # Taille de la fenêtre de zoom en Angstrom
n_line_zoom_plots: 6      # Nombre de plots de raies zoomées dans la mosaïque
plot_ultra_zoom: true     # Activer le zoom ultra-précis pour l'analyse Doppler

# --------------------------------------------------------------------------
# Logging des losses
# --------------------------------------------------------------------------
save_losses_csv: true     # Sauver les losses dans un fichier CSV
csv_save_every: 100       # Fréquence de sauvegarde CSV (en epochs)
csv_dir: "/content/drive/MyDrive/PFE/reports/logs"   # Répertoire pour les fichiers CSV

# --------------------------------------------------------------------------
# Phases d'entraînement
# --------------------------------------------------------------------------
# Liste d'étapes séquentielles, chacune avec ses propres optimiseur,
# hyperparamètres de scheduler et réglages de trainabilité.
phases:
  - name: rvonly
    n_epochs: 200
    optimizer: "torch.optim.Adam"                # Chemin complet de la classe
    optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.0
    b_obs_trainable: false
    b_rest_trainable: false
    # scheduler: "torch.optim.lr_scheduler.StepLR"
    # scheduler_kwargs:
    #   step_size: 50
    #   gamma: 0.5


  - name: joint
    n_epochs: 200
    optimizer: "torch.optim.Adam"
    optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.0
    b_obs_trainable: false
    b_rest_trainable: true
    scheduler: "torch.optim.lr_scheduler.StepLR"
    scheduler_kwargs:
      step_size: 50
      gamma: 0.7
    plot_spectra_every: 200     # Plot des spectres toutes les X epochs (0 = désactivé)
    spectra_plot_dir: "/content/drive/MyDrive/PFE/reports/spectra"  # Répertoire pour les plots de spectres
